### ISSUE TITLE
Landing page does not always take the user to the site they click on

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#46] opened 2021-03-07 08:44 UTC
As illustrated below, this is a fairly major usability bug I think so think it should be prioritised.

![Peek 2021-03-07 08-34](https://user-images.githubusercontent.com/1825120/110234246-3aad0d00-7f21-11eb-8424-dc95c8e4f469.gif)

**Comment by Siequnu** [comment] 2021-03-07 09:58
I'm not seeing this.
![ezgif-3-2b82a0c945f8](https://user-images.githubusercontent.com/11821606/110236041-ae293b80-7f6e-11eb-813c-ad7d54c2bd0a.gif)

**Comment by Robinlovelace** [comment] 2021-03-07 10:05
Tried on Firefox. Will try on Chrome now.

**Comment by Robinlovelace** [comment] 2021-03-07 10:07
Works on Chrome no probs. Will try on another laptop with Firefox to check it's not a cache issue...

**Comment by Robinlovelace** [comment] 2021-03-07 10:11
Confirmed, alas it seems browser specific. Can you reproduce on Firefox? Will try to make a GIF from my partner's laptop.

**Comment by Robinlovelace** [comment] 2021-03-07 10:13
On fairly typical laptop, Lenovo X240 that is using the site for the first time it shows the user:

![Peek 2021-03-07 10-12](https://user-images.githubusercontent.com/1825120/110236435-c167e700-7f2d-11eb-9bc5-c0edc2d4c1cd.gif)

**Comment by Siequnu** [comment] 2021-03-07 10:23
Good catch — I'll see what's going on!

**Comment by Siequnu** [comment] 2021-03-07 10:56
This is now fixed with the [latest commit](https://github.com/cyipt/actdev-ui/commit/c47d436d7d381acc297ca546ef396d83ae2df3f3).

The root cause is interesting: Gecko based browsers interpret a screen coordinate parameter differently to Webkit  c.f. [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=21868) and [Mozilla discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=674292).

**Comment by Robinlovelace** [comment] 2021-03-12 18:58
Sorry to say this has reared its head again. Affected @joeytalbot during live demo today. Successfully reproduced just now:

![Peek 2021-03-12 18-56](https://user-images.githubusercontent.com/1825120/110985888-e52f9080-8364-11eb-8fe2-be129a1b6e63.gif)

**Comment by mvl22** [comment] 2021-03-12 20:49
Yeah, I noticed this during the presentation. I'm looking at this but may need to wait for Patrick to pick this up. I've e-mailed him earlier with a possible better way to work out the link positions.

**Comment by mvl22** [comment] 2021-03-12 21:37
I've reworked this in 07aeb09d8794f09bbca90cb61ba0442c8a4815cc and it seems to be fine now, having tested combinations of all these:

- All three engines in widespread use (Chrome, Firefox, Safari)
- Different screen widths, including resized to mobile size
- After doing a scroll (which resets the window offset)

**Closed by mvl22** 2021-03-12 21:37 UTC
Labels: MVP, bug

**Comment by Robinlovelace** [comment] 2021-03-13 11:37
Outstanding work as always Martin. Thank you!
